package per.qoq.scrap.jobsdb.hibernate;
// Generated 2016/5/28 ¤W¤È 12:08:03 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Entity;

/**
 * CompanySumId generated by hbm2java
 */
@Entity
public class CompanySumId implements java.io.Serializable {

	private String companyName;
	private BigDecimal sum;

	public CompanySumId() {
	}

	public CompanySumId(String companyName, BigDecimal sum) {
		this.companyName = companyName;
		this.sum = sum;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public BigDecimal getSum() {
		return this.sum;
	}

	public void setSum(BigDecimal sum) {
		this.sum = sum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CompanySumId))
			return false;
		CompanySumId castOther = (CompanySumId) other;

		return ((this.getCompanyName() == castOther.getCompanyName()) || (this.getCompanyName() != null
				&& castOther.getCompanyName() != null && this.getCompanyName().equals(castOther.getCompanyName())))
				&& ((this.getSum() == castOther.getSum()) || (this.getSum() != null && castOther.getSum() != null
						&& this.getSum().equals(castOther.getSum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyName() == null ? 0 : this.getCompanyName().hashCode());
		result = 37 * result + (getSum() == null ? 0 : this.getSum().hashCode());
		return result;
	}

}
