package per.qoq.scrap.jobsdb.hibernate;
// Generated 2016/5/28 ¤W¤È 12:08:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.Entity;
import javax.persistence.ManyToOne;

/**
 * CompanySum generated by hbm2java
 */
@Entity
public class CompanySum implements java.io.Serializable {

	@ManyToOne
	private CompanySumId id;

	public CompanySum() {
	}

	public CompanySum(CompanySumId id) {
		this.id = id;
	}

	public CompanySumId getId() {
		return this.id;
	}

	public void setId(CompanySumId id) {
		this.id = id;
	}

}
